version: "3.1"
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
            - MYSQL_USER=easyappointments
            - MYSQL_PASSWORD=safepassword
        ports:
            - "8889:3306"
    server:
        build: .
        image: easyappointments-server:v1
        container_name: easyappointments
        ports:
            - "8888:8888"
        restart: always
        environment:
            - DEBUG=false
            - BASE_URL=http://207.180.214.153:8888
            - DB_HOST=db
            - DB_NAME=easyappointments
            - DB_USERNAME=easyappointments
            - DB_PASSWORD=safepassword
